plugins {
    id 'java'
    id 'war'
}

group = 'com.vit'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.1.0'
}

sourceSets {
    test {
        java {
            srcDirs = ['src/test/java']
        }
    }
}

tasks.register('demoTest', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.vit.demo.AppTest'
}

tasks.named('test') {
    dependsOn tasks.named('demoTest')
    enabled = false
}

war {
    archiveFileName = 'ci-jenkins-demo-1.0.0.war'
}

tasks.named('build') {
    dependsOn tasks.named('demoTest')
}
